const { Resend } = require('resend');
const { 
  Document, Packer, Paragraph, TextRun, 
  AlignmentType, BorderStyle,
  ShadingType, ImageRun
  } = require('docx');

function getResend() {
  return new Resend(process.env.RESEND_API_KEY);
}

async function sendWelcomeEmail(n, e, t) {
  try {
    await getResend().emails.send({
      from: 'Riya <hello@riya.co.za>',
      to: e,
      subject: 'Welcome to Riya — Your Broker Token',
      html: '<div style="margin:0;padding:40px 20px;background:#f4f4f4;font-family:Arial,sans-serif;"><div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;background:#ffffff;border-radius:8px;overflow:hidden;"><div style="background:#1F4E5F;padding:28px 32px;"><div style="color:#D4AF37;font-size:26px;font-weight:bold;">RIYA</div></div><div style="padding:32px;"><p>Dear ' + n + '</p><p>Welcome to Riya. Your token: <strong>' + t + '</strong></p><p><a href="https://riya-pilot.netlify.app">Open Riya</a></p><p>Toelie Pienaar<br/>083 325 8672</p></div></div></div>'
    });
    console.log('Welcome email sent to:', e);
  } catch(err) {
    console.error('Welcome email failed:', err.message);
  }
}

function parseRoAContent(rawText) {
  // Remove everything after "Client Acceptance" section footer
  const cutMarkers = [
    'Generated by Riya',
    'This is a basic acceptance record',
    'Client full name',
    'Confirm Acceptance'
  ];
  let cleanText = rawText;
  for (const marker of cutMarkers) {
    const idx = cleanText.indexOf(marker);
    if (idx !== -1) cleanText = cleanText.substring(0, idx);
  }

  // Remove duplicate sections — keep only content after last "---" separator
  // that precedes a section heading
  const parts = cleanText.split(/\n---\n/);
  
  // Find where real content starts (first occurrence of "1. FSP")
  let firstSectionIdx = -1;
  for (let i = 0; i < parts.length; i++) {
    if (/1\.\s+(FSP|RECORD OF ADVICE)/i.test(parts[i])) {
      firstSectionIdx = i;
      break;
    }
  }
  
  // Use only from first section onwards, deduplicate
  const seenSections = new Set();
  const dedupedParts = [];
  const relevantParts = firstSectionIdx >= 0 ? parts.slice(firstSectionIdx) : parts;
  
  for (const part of relevantParts) {
    const sectionMatch = part.match(/^\s*(\d+)\.\s+/m);
    if (sectionMatch) {
      const sectionNum = sectionMatch[1];
      if (!seenSections.has(sectionNum)) {
        seenSections.add(sectionNum);
        dedupedParts.push(part);
      }
    } else {
      dedupedParts.push(part);
    }
  }
  
  cleanText = dedupedParts.join('\n\n');

  // Now parse sections
  const sections = [];
  const lines = cleanText.split('\n');
  let currentSection = null;
  let currentContent = [];

  for (const line of lines) {
    const sectionMatch = line.match(/^(\d+)\.\s+(.+)/);
    if (sectionMatch) {
      if (currentSection) {
        sections.push({ title: currentSection, content: currentContent.join('\n').trim() });
      }
      currentSection = line.trim();
      currentContent = [];
    } else {
      currentContent.push(line);
    }
  }
  if (currentSection) {
    sections.push({ title: currentSection, content: currentContent.join('\n').trim() });
  }
  return { sections };
}

function buildWordDoc(clientName, brokerName, roaContent, brokerToken) {
  const fs = require('fs');
  const path = require('path');
  const DARK = '1B2A2F';
  const GOLD = 'C9A86A';
  const GREEN = '2E5E4E';
  const WHITE = 'FFFFFF';
  const { sections } = parseRoAContent(roaContent);
  const children = [];
// Add broker logo - top right
  try {
  const logoMap = {
      'RIYA-GOMES-001': { file: 'kensten-logo.png', width: 110, height: 80 },
      'RIYA-MARX-001': { file: '1st-insurance-logo.png', width: 150, height: 50 },
      'RIYA-CRAFFORD-0001': { file: 'twk-logo.png', width: 80, height: 80 },
      'RIYA-GROBLER-001': { file: 'galinco-logo.png', width: 140, height: 47 },
      'RIYA-TWK-001': { file: 'twk-logo.png', width: 80, height: 80 }, 'RIYA-APBCO-001': { file: 'apbco-logo.jpg', width: 120, height: 60 },
      'RIYA-BUXMAN-001': { file: 'million-bux-logo.png', width: 120, height: 44 }
    };  
    const logoConfig = logoMap[brokerToken];
    if (logoConfig) {
      const logoPath = path.join(__dirname, 'assets', logoConfig.file);
      if (fs.existsSync(logoPath)) {
        const logoBuffer = fs.readFileSync(logoPath);
        children.push(new Paragraph({
          alignment: AlignmentType.RIGHT,
          spacing: { after: 100 },
          children: [new ImageRun({ data: logoBuffer, transformation: { width: logoConfig.width, height: logoConfig.height }, type: 'png' })]
        }));
      }
    }
  } catch(logoErr) {
    console.warn('Word logo error:', logoErr.message);
  }


  children.push(new Paragraph({
    spacing: { after: 0 },
    shading: { fill: DARK, type: ShadingType.CLEAR },
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: 'RECORD OF ADVICE', bold: true, size: 36, color: WHITE, font: 'Arial' })]
  }));

  children.push(new Paragraph({
    spacing: { after: 200 },
    shading: { fill: GREEN, type: ShadingType.CLEAR },
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: 'FAIS & GCoC Compliant  |  Africa Bloom (Pty) Ltd  |  ' + new Date().toLocaleDateString('en-ZA'), size: 18, color: GOLD, font: 'Arial', italics: true })]
  }));

  children.push(new Paragraph({
    spacing: { before: 100, after: 200 },
    children: [
      new TextRun({ text: 'Client: ', bold: true, size: 22, font: 'Arial', color: DARK }),
      new TextRun({ text: clientName, size: 22, font: 'Arial', color: DARK })
    ]
  }));

  for (const section of sections) {
    if (section.title.toUpperCase().includes('RECORD OF ADVICE')) continue;

    children.push(new Paragraph({
      spacing: { before: 240, after: 80 },
      shading: { fill: DARK, type: ShadingType.CLEAR },
      border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: GOLD } },
      children: [new TextRun({ text: '  ' + section.title.toUpperCase() + '  ', bold: true, size: 22, color: GOLD, font: 'Arial' })]
    }));

    const contentLines = section.content.split('\n');
    for (const line of contentLines) {
      const trimmed = line.trim();
      if (!trimmed) { children.push(new Paragraph({ spacing: { after: 60 }, children: [] })); continue; }
      const isSubHeading = trimmed.endsWith(':') && trimmed.length < 60;
      const isBullet = trimmed.startsWith('•') || trimmed.startsWith('-') || trimmed.startsWith('*');

      if (isSubHeading) {
        children.push(new Paragraph({
          spacing: { before: 120, after: 60 },
          children: [new TextRun({ text: trimmed, bold: true, size: 20, font: 'Arial', color: GREEN })]
        }));
      } else if (isBullet) {
        children.push(new Paragraph({
          spacing: { after: 60 },
          indent: { left: 360 },
          children: [new TextRun({ text: trimmed, size: 20, font: 'Arial', color: DARK })]
        }));
      } else {
        children.push(new Paragraph({
          spacing: { after: 80 },
          children: [new TextRun({ text: trimmed, size: 20, font: 'Arial', color: DARK })]
        }));
      }
    }
  }

  children.push(new Paragraph({
    spacing: { before: 400 },
    shading: { fill: DARK, type: ShadingType.CLEAR },
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: 'Generated by Riya  |  Africa Bloom (Pty) Ltd  |  FAIS Act 37/2002  |  BN 80/2003  |  GN 706/2020', size: 16, color: GOLD, font: 'Arial', italics: true })]
  }));

  return new Document({
    sections: [{
      properties: { page: { margin: { top: 720, right: 720, bottom: 720, left: 720 } } },
      children
    }]
  });
}

async function sendRoAEmail(brokerEmail, clientName, brokerName, roaContent, brokerToken) {
  try {
    const wordDoc = buildWordDoc(clientName, brokerName, roaContent, brokerToken);
    const buffer = await Packer.toBuffer(wordDoc);
    const base64Content = buffer.toString('base64');
    await getResend().emails.send({
      from: 'Riya <hello@riya.co.za>',
      to: brokerEmail,
      subject: 'Record of Advice — ' + clientName + ' ' + new Date().toLocaleDateString('en-ZA'),
      html: '<div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;"><div style="background:#1B2A2F;padding:24px 32px;"><div style="color:#C9A86A;font-size:24px;font-weight:bold;letter-spacing:2px;">RIYA</div><div style="color:#ffffff;font-size:12px;margin-top:4px;font-style:italic;">An RoA that checks its own homework.</div></div><div style="padding:32px;background:#ffffff;"><p>Hi ' + (brokerName || 'Adviser') + ',</p><p>Please find attached the Record of Advice for <strong>' + clientName + '</strong>.</p><p>Please review carefully and make any edits needed before forwarding to your client.</p><p>Regards,<br/>Riya<br/>083 325 8672</p></div></div>',
      attachments: [{ filename: clientName.replace(/[^a-zA-Z0-9]/g, '_') + '_RoA.docx', content: base64Content }]
    });
    console.log('RoA email sent to:', brokerEmail);
    return { success: true };
  } catch(err) {
    console.error('RoA email failed:', err.message);
    return { success: false, error: err.message };
  }
}

module.exports = { sendWelcomeEmail, sendRoAEmail, parseRoAContent };
