const { Resend } = require('resend');
const {
  Document, Packer, Paragraph, TextRun,
  AlignmentType, BorderStyle, ShadingType, ImageRun, WidthType, Table, TableRow, TableCell
} = require('docx');

const NAVY = '1B2A4A';
const GOLD = 'C9A84C';
const DARK = '333333';
const WHITE = 'FFFFFF';
const LIGHT = 'F4F6F4';

function getResend() {
  return new Resend(process.env.RESEND_API_KEY);
}

async function sendWelcomeEmail(n, e, t) {
  try {
    await getResend().emails.send({
      from: 'Riya <hello@riya.co.za>',
      to: e,
      subject: 'Welcome to Riya — Your Broker Token',
      html: '<div style="margin:0;padding:40px 20px;background:#f4f4f4;font-family:Calibri,Arial,sans-serif;"><div style="max-width:600px;margin:0 auto;background:#ffffff;border-radius:4px;overflow:hidden;"><div style="text-align:right;padding:16px 28px 8px;border-bottom:2px solid #C9A84C;"><div style="color:#1B2A4A;font-size:15px;font-weight:bold;font-family:Calibri,Arial,sans-serif;">AFRICA BLOOM (PTY) LTD  |  T/A RIYA</div><div style="color:#C9A84C;font-size:11px;">toelie@riya.co.za  |  www.riya.co.za</div></div><div style="padding:32px;"><p style="color:#333;font-family:Calibri,Arial,sans-serif;">Dear ' + n + ',</p><p style="color:#333;font-family:Calibri,Arial,sans-serif;">Welcome to Riya. Your broker token: <strong style="color:#1B2A4A;">' + t + '</strong></p><p><a href="https://riya-pilot.netlify.app" style="background:#1B2A4A;color:#C9A84C;padding:10px 20px;text-decoration:none;border-radius:3px;font-family:Calibri,Arial,sans-serif;">Open Riya</a></p><p style="color:#333;font-family:Calibri,Arial,sans-serif;">Toelie Pienaar<br/>083 325 8672</p></div><div style="padding:12px 28px;border-top:2px solid #C9A84C;text-align:center;"><span style="color:#C9A84C;font-size:10px;font-family:Calibri,Arial,sans-serif;">Riya — Africa Bloom (Pty) Ltd  |  FAIS Act 37/2002  |  BN 80/2003  |  GN 706/2020</span></div></div></div>'
    });
    console.log('Welcome email sent to:', e);
  } catch(err) {
    console.error('Welcome email failed:', err.message);
  }
}

function parseRoAContent(rawText) {
  const cutMarkers = ['Generated by Riya', 'This is a basic acceptance record', 'Client full name', 'Confirm Acceptance'];
  let cleanText = rawText;
  for (const marker of cutMarkers) {
    const idx = cleanText.indexOf(marker);
    if (idx !== -1) cleanText = cleanText.substring(0, idx);
  }
  const parts = cleanText.split(/\n---\n/);
  let firstSectionIdx = -1;
  for (let i = 0; i < parts.length; i++) {
    if (/1\.\s+(FSP|RECORD OF ADVICE)/i.test(parts[i])) { firstSectionIdx = i; break; }
  }
  const seenSections = new Set();
  const dedupedParts = [];
  const relevantParts = firstSectionIdx >= 0 ? parts.slice(firstSectionIdx) : parts;
  for (const part of relevantParts) {
    const sectionMatch = part.match(/^\s*(\d+)\.\s+/m);
    if (sectionMatch) {
      const sectionNum = sectionMatch[1];
      if (!seenSections.has(sectionNum)) { seenSections.add(sectionNum); dedupedParts.push(part); }
    } else { dedupedParts.push(part); }
  }
  cleanText = dedupedParts.join('\n\n');
  const sections = [];
  const lines = cleanText.split('\n');
  let currentSection = null;
  let currentContent = [];
  for (const line of lines) {
    const sectionMatch = line.match(/^(\d+)\.\s+(.+)/);
    if (sectionMatch) {
      if (currentSection) sections.push({ title: currentSection, content: currentContent.join('\n').trim() });
      currentSection = line.trim();
      currentContent = [];
    } else { currentContent.push(line); }
  }
  if (currentSection) sections.push({ title: currentSection, content: currentContent.join('\n').trim() });
  return { sections };
}

function buildWordDoc(clientName, brokerName, roaContent, brokerToken, adviceDate, triggerLabel) {
  const fs = require('fs');
  const path = require('path');
  const { sections } = parseRoAContent(roaContent);
  const children = [];

  // ===== HEADER — right-aligned =====
  children.push(new Paragraph({
    alignment: AlignmentType.RIGHT,
    spacing: { after: 40 },
    children: [new TextRun({ text: 'AFRICA BLOOM (PTY) LTD  |  T/A RIYA', bold: true, size: 24, color: NAVY, font: 'Calibri' })]
  }));
  children.push(new Paragraph({
    alignment: AlignmentType.RIGHT,
    spacing: { after: 0 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 12, color: GOLD } },
    children: [new TextRun({ text: 'toelie@riya.co.za  |  www.riya.co.za', size: 18, color: GOLD, font: 'Calibri' })]
  }));

  // ===== LOGO — top right =====
  try {
    const logoMap = {
      'RIYA-GOMES-001': { file: 'kensten-logo.png', width: 110, height: 80 },
      'RIYA-MARX-001': { file: '1st-insurance-logo.png', width: 150, height: 50 },
      'RIYA-CRAFFORD-0001': { file: 'twk-logo.png', width: 80, height: 80 },
      'RIYA-GROBLER-001': { file: 'galinco-logo.png', width: 140, height: 47 },
      'RIYA-TWK-001': { file: 'twk-logo.png', width: 80, height: 80 },
      'RIYA-APBCO-001': { file: 'apbco-logo.jpg', width: 120, height: 60 },
      'RIYA-LIBRA-001': { file: 'Libra-Brokers-Logo.png', width: 90, height: 60 },
      'RIYA-BUXMAN-001': { file: 'million-bux-logo.png', width: 120, height: 44 }
    };
    const logoConfig = logoMap[brokerToken];
    if (logoConfig) {
      const logoPath = path.join(__dirname, 'assets', logoConfig.file);
      if (fs.existsSync(logoPath)) {
        const logoBuffer = fs.readFileSync(logoPath);
        children.push(new Paragraph({
          alignment: AlignmentType.RIGHT,
          spacing: { before: 80, after: 80 },
          children: [new ImageRun({ data: logoBuffer, transformation: { width: logoConfig.width, height: logoConfig.height }, type: 'png' })]
        }));
      }
    }
  } catch(logoErr) { console.warn('Word logo error:', logoErr.message); }

  // ===== TITLE =====
  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 120, after: 60 },
    children: [new TextRun({ text: 'RECORD OF ADVICE', bold: true, size: 36, color: NAVY, font: 'Calibri' })]
  }));
  children.push(new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 0 },
    border: { bottom: { style: BorderStyle.SINGLE, size: 12, color: GOLD } },
    children: [new TextRun({ text: (triggerLabel || 'Record of Advice') + '  |  ' + (adviceDate || new Date().toLocaleDateString('en-ZA')), size: 20, color: GOLD, font: 'Calibri', italics: true })]
  }));

  // ===== SECTIONS =====
  for (const section of sections) {
    if (section.title.toUpperCase().includes('RECORD OF ADVICE')) continue;

    // Section heading — navy bold + gold underline (agreement style)
    children.push(new Paragraph({
      spacing: { before: 280, after: 0 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: GOLD } },
      children: [new TextRun({ text: section.title.toUpperCase(), bold: true, size: 22, color: NAVY, font: 'Calibri' })]
    }));

    const contentLines = section.content.replace(/OU[\s\n]+Tsurance/g,"OUTsurance").split('\n');
    for (const line of contentLines) {
      const trimmed = line.trim();
      if (!trimmed) {
        children.push(new Paragraph({ spacing: { after: 60 }, children: [] }));
        continue;
      }

      const isBullet = trimmed.startsWith('•') || trimmed.startsWith('\u2022') || trimmed.startsWith('-') || trimmed.startsWith('*');
      const isSubHeading = !isBullet && trimmed.endsWith(':') && trimmed.length < 70;
      const isSignatureLine = /^(Client Signature|Client Name|Adviser Signature|Adviser Name|Date):/.test(trimmed);

      if (isSubHeading) {
        children.push(new Paragraph({
          spacing: { before: 120, after: 60 },
          children: [new TextRun({ text: trimmed, bold: true, size: 21, color: NAVY, font: 'Calibri' })]
        }));
      } else if (isBullet) {
        const bulletText = trimmed.replace(/^[•\u2022\-\*]\s*/, '');
        children.push(new Paragraph({
          spacing: { after: 60 },
          indent: { left: 360 },
          children: [
            new TextRun({ text: '\u2022  ', bold: true, color: GOLD, size: 21, font: 'Calibri' }),
            new TextRun({ text: bulletText, size: 21, color: DARK, font: 'Calibri' })
          ]
        }));
      } else if (isSignatureLine) {
        children.push(new Paragraph({
          spacing: { before: 160, after: 160 },
          children: [new TextRun({ text: trimmed, size: 21, color: DARK, font: 'Calibri' })]
        }));
      } else {
        children.push(new Paragraph({
          spacing: { after: 80 },
          children: [new TextRun({ text: trimmed, size: 21, color: DARK, font: 'Calibri' })]
        }));
      }
    }
  }

  // ===== FOOTER =====
  children.push(new Paragraph({
    spacing: { before: 400, after: 0 },
    border: { top: { style: BorderStyle.SINGLE, size: 12, color: GOLD } },
    alignment: AlignmentType.CENTER,
    children: [new TextRun({ text: 'Riya — Africa Bloom (Pty) Ltd  |  toelie@riya.co.za  |  POPIA Compliant  |  FAIS Act 37/2002  |  BN 80/2003  |  GN 706/2020  |  5-year retention required', size: 16, color: GOLD, font: 'Calibri', italics: true })]
  }));

  return new Document({
    sections: [{
      properties: { page: { margin: { top: 720, right: 860, bottom: 720, left: 860 } } },
      children
    }]
  });
}

function buildClientEmailHtml(clientName, brokerName, roaContent, signatureLink) {
  const { sections } = parseRoAContent(roaContent);

  let sectionsHtml = '';
  for (const section of sections) {
    if (section.title.toUpperCase().includes('RECORD OF ADVICE')) continue;
    sectionsHtml += `
      <div style="margin-top:24px;">
        <div style="font-weight:bold;font-size:13px;color:#1B2A4A;font-family:Calibri,Arial,sans-serif;border-bottom:2px solid #C9A84C;padding-bottom:4px;margin-bottom:8px;">${section.title.toUpperCase()}</div>
        <div style="font-size:12px;color:#333;font-family:Calibri,Arial,sans-serif;line-height:1.7;">
    `;
    const lines = section.content.split('\n');
    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) { sectionsHtml += '<br/>'; continue; }
      const isBullet = trimmed.startsWith('•') || trimmed.startsWith('\u2022') || trimmed.startsWith('-') || trimmed.startsWith('*');
      const isSubHeading = !isBullet && trimmed.endsWith(':') && trimmed.length < 70;
      if (isSubHeading) {
        sectionsHtml += `<div style="font-weight:bold;color:#1B2A4A;margin-top:8px;">${trimmed}</div>`;
      } else if (isBullet) {
        const bulletText = trimmed.replace(/^[•\u2022\-\*]\s*/, '');
        sectionsHtml += `<div style="padding-left:16px;">&#8226;&nbsp;&nbsp;${bulletText}</div>`;
      } else {
        sectionsHtml += `<div>${trimmed}</div>`;
      }
    }
    sectionsHtml += '</div></div>';
  }

  const signatureSection = signatureLink ? `
    <div style="margin-top:32px;padding:20px;background:#F4F6F4;border-left:4px solid #C9A84C;border-radius:3px;">
      <div style="font-weight:bold;color:#1B2A4A;font-family:Calibri,Arial,sans-serif;margin-bottom:8px;">Electronic Acceptance</div>
      <div style="font-size:12px;color:#333;font-family:Calibri,Arial,sans-serif;margin-bottom:12px;">Please review this Record of Advice carefully. If you accept the advice and recommendation, click the button below to record your acceptance.</div>
      <a href="${signatureLink}" style="display:inline-block;background:#1B2A4A;color:#C9A84C;padding:12px 24px;text-decoration:none;border-radius:3px;font-family:Calibri,Arial,sans-serif;font-weight:bold;font-size:13px;">Accept this Record of Advice</a>
    </div>
  ` : '';

  return `
    <div style="margin:0;padding:40px 20px;background:#F4F6F4;font-family:Calibri,Arial,sans-serif;">
      <div style="max-width:680px;margin:0 auto;background:#ffffff;border-radius:4px;overflow:hidden;">
        
        <!-- Header -->
        <div style="text-align:right;padding:16px 28px 8px;border-bottom:2px solid #C9A84C;">
          <div style="color:#1B2A4A;font-size:15px;font-weight:bold;font-family:Calibri,Arial,sans-serif;">AFRICA BLOOM (PTY) LTD  |  T/A RIYA</div>
          <div style="color:#C9A84C;font-size:11px;font-family:Calibri,Arial,sans-serif;">toelie@riya.co.za  |  www.riya.co.za</div>
        </div>

        <div style="padding:32px;">

          <!-- Title -->
          <div style="text-align:center;margin-bottom:24px;">
            <div style="font-size:22px;font-weight:bold;color:#1B2A4A;font-family:Calibri,Arial,sans-serif;letter-spacing:1px;">RECORD OF ADVICE</div>
            <div style="color:#C9A84C;font-size:11px;font-style:italic;margin-top:4px;padding-bottom:12px;border-bottom:2px solid #C9A84C;">FAIS &amp; GCoC Compliant</div>
          </div>

          <p style="color:#333;font-family:Calibri,Arial,sans-serif;font-size:13px;">Dear ${clientName},</p>
          <p style="color:#333;font-family:Calibri,Arial,sans-serif;font-size:12px;">Please find below your Record of Advice prepared by <strong>${brokerName || 'your adviser'}</strong>. Kindly review all sections carefully before accepting.</p>

          <!-- RoA Content -->
          ${sectionsHtml}

          <!-- Electronic Acceptance -->
          ${signatureSection}

        </div>

        <!-- Footer -->
        <div style="padding:12px 28px;border-top:2px solid #C9A84C;text-align:center;background:#fff;">
          <span style="color:#C9A84C;font-size:9px;font-family:Calibri,Arial,sans-serif;">Riya — Africa Bloom (Pty) Ltd  |  toelie@riya.co.za  |  POPIA Compliant  |  FAIS Act 37/2002  |  BN 80/2003  |  GN 706/2020  |  5-year retention required</span>
        </div>
      </div>
    </div>
  `;
}

async function sendRoAEmail(brokerEmail, clientName, brokerName, roaContent, brokerToken, adviceDate, triggerLabel) {
  try {
    const wordDoc = buildWordDoc(clientName, brokerName, roaContent, brokerToken, adviceDate, triggerLabel);
    const buffer = await Packer.toBuffer(wordDoc);
    const base64Content = buffer.toString('base64');
    const dateStr = adviceDate || new Date().toLocaleDateString('en-ZA');
    await getResend().emails.send({
      from: 'Riya <hello@riya.co.za>',
      to: brokerEmail,
      subject: 'Record of Advice — ' + clientName + ' — ' + dateStr,
      html: `<div style="font-family:Calibri,Arial,sans-serif;max-width:600px;margin:0 auto;">
        <div style="text-align:right;padding:16px 28px 8px;border-bottom:2px solid #C9A84C;">
          <div style="color:#1B2A4A;font-size:15px;font-weight:bold;">AFRICA BLOOM (PTY) LTD  |  T/A RIYA</div>
          <div style="color:#C9A84C;font-size:11px;">toelie@riya.co.za  |  www.riya.co.za</div>
        </div>
        <div style="padding:32px;background:#ffffff;">
          <p style="color:#333;">Hi ${brokerName || 'Adviser'},</p>
          <p style="color:#333;">Please find attached the Record of Advice for <strong style="color:#1B2A4A;">${clientName}</strong>.</p>
          <p style="color:#333;">Please review carefully and make any necessary edits before forwarding to your client.</p>
          <p style="color:#333;">Regards,<br/><strong>Riya</strong><br/>083 325 8672</p>
        </div>
        <div style="padding:12px 28px;border-top:2px solid #C9A84C;text-align:center;">
          <span style="color:#C9A84C;font-size:9px;">Riya — Africa Bloom (Pty) Ltd  |  FAIS Act 37/2002  |  BN 80/2003  |  GN 706/2020</span>
        </div>
      </div>`,
      attachments: [{ filename: clientName.replace(/[^a-zA-Z0-9]/g, '_') + '_RoA.docx', content: base64Content }]
    });
    console.log('RoA email sent to:', brokerEmail);
    return { success: true };
  } catch(err) {
    console.error('RoA email failed:', err.message);
    return { success: false, error: err.message };
  }
}

async function sendRoAToClient(clientEmail, clientName, brokerName, roaContent, brokerToken, acceptanceUrl, triggerLabel, adviceDate) {
  try {
    const dateStr = adviceDate || new Date().toLocaleDateString('en-ZA');
    const html = `<div style="margin:0;padding:40px 20px;background:#F4F6F4;font-family:Calibri,Arial,sans-serif;">
      <div style="max-width:600px;margin:0 auto;background:#ffffff;border-radius:4px;overflow:hidden;">
        <div style="text-align:right;padding:16px 28px 8px;border-bottom:2px solid #C9A84C;">
          <div style="color:#1B2A4A;font-size:15px;font-weight:bold;font-family:Calibri,Arial,sans-serif;">AFRICA BLOOM (PTY) LTD  |  T/A RIYA</div>
          <div style="color:#C9A84C;font-size:11px;font-family:Calibri,Arial,sans-serif;">toelie@riya.co.za  |  www.riya.co.za</div>
        </div>
        <div style="padding:32px;">
          <div style="text-align:center;margin-bottom:24px;">
            <div style="font-size:20px;font-weight:bold;color:#1B2A4A;font-family:Calibri,Arial,sans-serif;letter-spacing:1px;">RECORD OF ADVICE</div>
            <div style="color:#C9A84C;font-size:11px;font-style:italic;margin-top:4px;padding-bottom:10px;border-bottom:2px solid #C9A84C;">${triggerLabel || 'Record of Advice'}  |  ${dateStr}</div>
          </div>
          <p style="color:#333;font-family:Calibri,Arial,sans-serif;font-size:13px;">Dear ${clientName},</p>
          <p style="color:#333;font-family:Calibri,Arial,sans-serif;font-size:13px;line-height:1.6;margin-top:12px;">
            <strong>${brokerName || 'Your adviser'}</strong> has prepared a Record of Advice for your review. This document sets out the insurance advice provided to you and requires your acceptance before your policy can be placed.
          </p>
          <p style="color:#333;font-family:Calibri,Arial,sans-serif;font-size:13px;line-height:1.6;margin-top:12px;">
            Please click the button below to read the full Record of Advice and confirm your acceptance.
          </p>
          <div style="text-align:center;margin:28px 0;">
            <a href="${acceptanceUrl}" style="display:inline-block;background:#1B2A4A;color:#C9A84C;padding:14px 32px;text-decoration:none;border-radius:3px;font-family:Calibri,Arial,sans-serif;font-weight:bold;font-size:14px;letter-spacing:1px;">Review &amp; Accept Record of Advice</a>
          </div>
          <p style="color:#999;font-family:Calibri,Arial,sans-serif;font-size:11px;line-height:1.6;margin-top:12px;">
            This link is valid for 30 days. If you have any questions, please contact your broker directly.
          </p>
        </div>
        <div style="padding:12px 28px;border-top:2px solid #C9A84C;text-align:center;background:#fff;">
          <span style="color:#C9A84C;font-size:9px;font-family:Calibri,Arial,sans-serif;">Riya — Africa Bloom (Pty) Ltd  |  toelie@riya.co.za  |  POPIA Compliant  |  FAIS Act 37/2002  |  BN 80/2003  |  GN 706/2020</span>
        </div>
      </div>
    </div>`;
    await getResend().emails.send({
      from: 'Riya <hello@riya.co.za>',
      to: clientEmail,
      subject: 'Your Record of Advice — ' + clientName,
      html
    });
    console.log('Client RoA email sent to:', clientEmail);
    return { success: true };
  } catch(err) {
    console.error('Client RoA email failed:', err.message);
    return { success: false, error: err.message };
  }
}

module.exports = { sendWelcomeEmail, sendRoAEmail, sendRoAToClient, parseRoAContent, buildWordDoc };
