const { Resend } = require('resend');
const resend = new Resend(process.env.RESEND_API_KEY);
async function sendWelcomeEmail(n, e, t) {
  try {
    await resend.emails.send({
      from: 'Riya <hello@riya.co.za>',
      to: e,
      subject: 'Welcome to Riya — Your Broker Token',
      html: '<div style="margin:0;padding:40px 20px;background:#f4f4f4;font-family:Arial,sans-serif;"><div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;background:#ffffff;border-radius:8px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1);"><div style="background:#1F4E5F;padding:28px 32px;"><div style="color:#D4AF37;font-size:26px;font-weight:bold;letter-spacing:1px;">RIYA</div><div style="color:#ffffff;font-size:13px;font-style:italic;margin-top:4px;opacity:0.9;">An RoA that checks its own homework.</div></div><div style="padding:32px;"><p style="font-size:15px;color:#1A1A1A;line-height:1.6;margin-top:0;">Dear ' + n + '</p><p style="font-size:15px;color:#1A1A1A;line-height:1.6;">Welcome to Riya. You\u2019re now set up with <strong>5 free Records of Advice</strong> to try it for yourself.</p><p style="font-size:15px;color:#1A1A1A;line-height:1.6;">Paste your notes, upload a file, or upload a voice note from a client call — Riya extracts the details, flags anything still missing, and drafts a complete, FAIS-compliant RoA in minutes, not 30–45.</p><div style="background:#F7F5EF;border:1px solid #E0DCC8;border-radius:6px;padding:18px 20px;margin:24px 0;text-align:center;"><div style="font-size:11px;color:#595959;text-transform:uppercase;letter-spacing:1px;margin-bottom:6px;">Your Broker Token</div><div style="font-size:22px;font-weight:bold;color:#1F4E5F;font-family:\'Courier New\',monospace;">' + t + '</div></div><div style="text-align:center;margin:28px 0;"><a href="https://riya-pilot.netlify.app" style="background:#1F4E5F;color:#ffffff;text-decoration:none;padding:13px 32px;border-radius:4px;font-size:14px;font-weight:bold;display:inline-block;">Open Riya &amp; Enter Your Token</a></div><p style="font-size:13px;color:#595959;line-height:1.6;">After your free credits: R10 for personal lines, R15 for commercial — per RoA, no subscription.</p><hr style="border:none;border-top:1px solid #E5E5E5;margin:28px 0;"><p style="font-size:14px;color:#1A1A1A;line-height:1.6;">I built Riya after almost 30 years in SA short-term insurance, watching good brokers lose hours to paperwork that should take minutes. If anything doesn\u2019t feel right while you\u2019re trying it, tell me directly — I\u2019m building this with brokers, not just for them.</p><p style="font-size:14px;color:#1A1A1A;line-height:1.6;margin-bottom:0;">Toelie Pienaar<br><a href="tel:0833258672" style="color:#1F4E5F;text-decoration:none;">083 325 8672</a></p></div><div style="background:#FAFAFA;padding:16px 32px;border-top:1px solid #EEEEEE;"><div style="font-size:11px;color:#999999;">Africa Bloom (Pty) Ltd &middot; riya.co.za</div></div></div></div>'
    });
    console.log('Email sent to:', e);
  } catch(err) {
    console.error('Email failed:', err.message);
  }
}
module.exports = { sendWelcomeEmail };